org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djavax.net.ssl.trustStore=C\:\\Users\\msaya\\.android\\custom-cacerts -Djavax.net.ssl.trustStorePassword=changeit
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
