/**
 * Supabase database types for the Marketing Landing Site.
 *
 * The `Database` type follows the @supabase/supabase-js typed client pattern
 * and describes the `marketing_leads` table used for lead capture.
 */

/** Tier of interest enum values matching the DB check constraint. */
export type TierOfInterest = 'starter' | 'growth' | 'enterprise';

/** Row shape as stored in the `marketing_leads` table. */
export interface MarketingLeadRow {
  id: string;
  created_at: string;
  organization_name: string;
  contact_name: string;
  email: string;
  role: string | null;
  country: string | null;
  mfi_size: string | null;
  message: string;
  tier_of_interest: TierOfInterest | null;
  source_page: string | null;
  user_agent: string | null;
}

/**
 * Insert shape for the `marketing_leads` table.
 * `id` and `created_at` are generated by the database and omitted from inserts.
 */
export type MarketingLeadInsert = Omit<MarketingLeadRow, 'id' | 'created_at'>;

/**
 * Client-side lead submission payload (camelCase).
 * Used by the ContactForm before transformation to snake_case for the DB insert.
 */
export interface LeadSubmission {
  organizationName: string;
  contactName: string;
  email: string;
  message: string;
  role?: string;
  country?: string;
  mfiSize?: string;
  tierOfInterest?: TierOfInterest;
  sourcePage?: string;
}

/**
 * Discriminated union returned by the `submitLead` server action.
 */
export type LeadSubmissionResult =
  | { ok: true }
  | { ok: false; code: 'invalid' | 'rejected' | 'server_error'; fieldErrors?: Record<string, string> };

/**
 * Database type compatible with `createClient<Database>(...)` from @supabase/supabase-js.
 * Only the `public` schema and `marketing_leads` table are defined since
 * the marketing site does not interact with other tables.
 */
export interface Database {
  public: {
    Tables: {
      marketing_leads: {
        Row: MarketingLeadRow;
        Insert: MarketingLeadInsert;
        Update: Partial<MarketingLeadInsert>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      tier_of_interest: TierOfInterest;
    };
    CompositeTypes: Record<string, never>;
  };
}
